[package]
name = "goxlr-client"
version = "0.4.0"
edition = "2021"
build = "build.rs"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>", "Craig McLure <craig@mclure.net>", "Lars Mühlbauer <lm41@dismail.de>"]
description = "Allows control of a TC-Helicon GoXLR or GoXLR Mini, by interacting with a running daemon."
repository = "https://github.com/GoXLR-on-Linux/GoXLR-Utility"
license = "MIT"
categories = ["hardware-support", "command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goxlr-ipc = {path = "../ipc"}
goxlr-types = { path = "../types", features = ["clap"] }
tokio = {version = "1.0", features=["full"]}
simplelog = "0.11.1"
anyhow = "1.0"
clap = { version = "3.0.0", features = ["derive"] }
strum = { version = "0.23"}
serde_json = { version = "1.0" }
tokio-serde = { version = "0.8.0", features=["json"]}

[build-dependencies]
clap = { version = "3.0.0", features = ["derive"] }
clap_complete = "3.0.0"
goxlr-types = { path = "../types", features = ["clap"] }
