[package]
name = "goxlr-launcher"
version = "1.0.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
goxlr-ipc = { path = "../ipc" }
goxlr-types = { path = "../types" }

interprocess = { version = "1.2.1", features=["tokio_support"] }
tokio = { version = "1.35.0", features=["full"] }
which = "5.0.0"

[target.'cfg(windows)'.dependencies]
tasklist = { git = "https://github.com/yalishandar/tasklist-rs.git" }

[target.'cfg(target_family = "unix")'.dependencies]
nix = { version =  "0.27.1", features = ["process"] }
sysinfo = "0.29.11"

[target.'cfg(target_os = "windows")'.build-dependencies]
windres = "0.2.2"
