[package]
name = "goxlr-usb"
version = "0.1.0"
edition = "2021"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>", "Craig McLure <craig@mclure.net>", "Lars Mühlbauer <lm41@dismail.de>"]
description = "A direct interface to the TC-Helicon GoXLR & GoXLR Mini via usb."
repository = "https://github.com/GoXLR-on-Linux/GoXLR-Utility"
license = "MIT"
categories = ["hardware-support", "api-bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goxlr-types = {path = "../types"}
rusb = "0.9"
thiserror = "1.0"
byteorder = "1"
log = "0.4.14"
enumset = "1.0.8"
strum = "0.23.0"
