[package]
name = "goxlr-scribbles"
version = "1.0.1"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
imageproc = "0.23.0"
rusttype = "0.9.3"
anyhow = "1.0.68"
log = "0.4.17"
